"use client";
import {useMemo,useState} from "react";
type CV={name:string;role:string;email:string;phone:string;location:string;summary:string;skills:string;job:string;company:string;dates:string;bullets:string;degree:string;school:string;project:string;projectText:string};
const blank:CV={name:"",role:"",email:"",phone:"",location:"",summary:"",skills:"",job:"",company:"",dates:"",bullets:"",degree:"",school:"",project:"",projectText:""};
const example:CV={name:"Maya Perera",role:"Junior Software Engineer",email:"maya@email.com",phone:"+94 77 123 4567",location:"Colombo, Sri Lanka",summary:"Detail-oriented software engineering graduate with experience building accessible web applications and solving real user problems.",skills:"JavaScript, TypeScript, React, Next.js, Node.js, SQL, Git",job:"Software Engineering Intern",company:"Nova Digital",dates:"Jan 2025 — Jun 2025",bullets:"Built reusable React components that reduced development time by 25%.\nCollaborated with designers and engineers to deliver customer-facing features.\nImproved page performance and accessibility.",degree:"BSc (Hons) in Software Engineering",school:"University of Colombo",project:"Campus Connect",projectText:"Built a full-stack platform helping students discover clubs and university events."};
const tabs=["Personal","Summary","Education","Experience","Projects","Skills"] as const;type Tab=typeof tabs[number];
export default function Builder(){const[cv,setCv]=useState(blank),[tab,setTab]=useState<Tab>("Personal"),[mobile,setMobile]=useState<"edit"|"preview">("edit");const set=(k:keyof CV,v:string)=>setCv(o=>({...o,[k]:v}));const score=Math.round(Object.values(cv).filter(Boolean).length/Object.keys(cv).length*100);const issues=useMemo(()=>[!cv.name&&"Add your name",!cv.role&&"Add a target title",!cv.summary&&"Write a summary",!cv.skills&&"Add relevant skills"].filter(Boolean) as string[],[cv]);const exportData=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(cv,null,2)],{type:"application/json"}));a.download="cvolt-cv.json";a.click()};return <main className="builder-app">
<header className="app-header"><div className="app-head-main"><a className="brand app-brand" href="/"><span>CV</span>OLT<span className="brand-dot">.</span></a><div><div className="app-title-row"><h1>CV Builder</h1><span className="status-chip blue">✦ ATS ready</span><span className="status-chip green">● In-memory only</span></div><p>Build, check, and download your professional CV.</p></div></div><div className="memory-note">◉ No autosave. Refreshing or closing clears current edits.</div><div className="app-actions"><button onClick={()=>setCv(blank)}>↻ New CV</button><button onClick={exportData}>{"{}"} Export JSON</button><button className="action-primary" onClick={()=>window.print()}>↓ Download PDF</button></div></header>
<div className="mobile-switch"><button className={mobile==="edit"?"active":""} onClick={()=>setMobile("edit")}>✎ Edit</button><button className={mobile==="preview"?"active":""} onClick={()=>setMobile("preview")}>▤ Preview</button></div>
<div className="app-grid"><aside className={"app-sidebar "+(mobile==="preview"?"mobile-off":"")}><div className="score-card"><div className="score-number"><strong>{score}</strong><span>/100</span></div><div><b>{score<50?"Good start":score<85?"Almost ready":"Application ready"}</b><p>{issues.length?issues.length+" improvements recommended":"All essentials completed"}</p></div></div><nav>{tabs.map((t,i)=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}><span>{["◎","≡","◇","▣","▤","✦"][i]}</span>{t}<b>{done(t,cv)?"✓":""}</b></button>)}</nav><div className="tips"><strong>ATS checklist</strong>{issues.length?issues.map(x=><p key={x}>○ {x}</p>):<p>✓ Essential content is ready.</p>}<button onClick={()=>setCv(example)}>Load example CV</button></div></aside>
<section className={"editor-card "+(mobile==="preview"?"mobile-off":"")}><div className="editor-head"><div><small>SECTION {tabs.indexOf(tab)+1} OF 6</small><h2>{tab}</h2><p>{help(tab)}</p></div><span>{done(tab,cv)?"✓ Complete":"In progress"}</span></div><div className="editor-body">
{tab==="Personal"&&<div className="app-form"><F label="Full name" value={cv.name} change={v=>set("name",v)} placeholder="YOUR NAME"/><F label="Target job title" value={cv.role} change={v=>set("role",v)} placeholder="SOFTWARE ENGINEER"/><F label="Email" value={cv.email} change={v=>set("email",v)} placeholder="name@example.com"/><F label="Phone" value={cv.phone} change={v=>set("phone",v)} placeholder="+94 70 123 4567"/><F label="Location" value={cv.location} change={v=>set("location",v)} placeholder="City, Country"/></div>}
{tab==="Summary"&&<A label="Professional summary" value={cv.summary} change={v=>set("summary",v)} placeholder="Write 3–4 concise sentences tailored to your target role."/>}
{tab==="Education"&&<div className="app-form"><F label="Degree / qualification" value={cv.degree} change={v=>set("degree",v)} placeholder="BSc in Software Engineering"/><F label="School / university" value={cv.school} change={v=>set("school",v)} placeholder="University name"/></div>}
{tab==="Experience"&&<div className="app-form"><F label="Job title" value={cv.job} change={v=>set("job",v)} placeholder="Software Engineering Intern"/><F label="Company" value={cv.company} change={v=>set("company",v)} placeholder="Company name"/><F label="Dates" value={cv.dates} change={v=>set("dates",v)} placeholder="Jan 2025 — Jun 2025"/><A label="Achievements — one per line" value={cv.bullets} change={v=>set("bullets",v)} placeholder="Start with action verbs and include measurable results."/></div>}
{tab==="Projects"&&<div className="app-form"><F label="Project name" value={cv.project} change={v=>set("project",v)} placeholder="Project name"/><A label="What you built and achieved" value={cv.projectText} change={v=>set("projectText",v)} placeholder="Describe the problem, your contribution, tools, and result."/></div>}
{tab==="Skills"&&<A label="Relevant skills — separated with commas" value={cv.skills} change={v=>set("skills",v)} placeholder="JavaScript, React, Node.js, SQL, Git"/>}</div>
<div className="editor-footer"><button disabled={tabs.indexOf(tab)===0} onClick={()=>setTab(tabs[tabs.indexOf(tab)-1])}>← Previous</button><button className="action-primary" onClick={()=>{const i=tabs.indexOf(tab);if(i<5)setTab(tabs[i+1]);else setMobile("preview")}}>{tab==="Skills"?"Preview CV":"Save & continue →"}</button></div></section>
<section className={"app-preview "+(mobile==="edit"?"mobile-off-preview":"")}><div className="preview-head"><div><b>Live preview</b><span>A4 • 1 page</span></div><div><button onClick={()=>setCv(example)}>Use example</button><button className="action-primary" onClick={()=>window.print()}>↓ PDF</button></div></div><div className="preview-canvas"><Resume cv={cv}/></div></section></div></main>}
function done(t:Tab,c:CV){return t==="Personal"?!!(c.name&&c.role&&c.email):t==="Summary"?!!c.summary:t==="Education"?!!(c.degree&&c.school):t==="Experience"?!!(c.job&&c.company):t==="Projects"?!!(c.project&&c.projectText):!!c.skills}function help(t:Tab){return({Personal:"Contact details shown at the top of your CV.",Summary:"A concise introduction tailored to the role you want.",Education:"Your most relevant qualification.",Experience:"Focus on achievements and measurable impact.",Projects:"Practical work that proves your skills.",Skills:"Role-relevant keywords recruiters may search."})[t]}function F(p:{label:string;value:string;change:(v:string)=>void;placeholder:string}){return <label><span>{p.label}</span><input value={p.value} onChange={e=>p.change(e.target.value)} placeholder={p.placeholder}/></label>}function A(p:{label:string;value:string;change:(v:string)=>void;placeholder:string}){return <label className="area-field"><span>{p.label}</span><textarea rows={8} value={p.value} onChange={e=>p.change(e.target.value)} placeholder={p.placeholder}/></label>}function R({title,children}:{title:string;children:React.ReactNode}){return <section className="resume-section"><h2>{title}</h2>{children}</section>}function Resume({cv}:{cv:CV}){const empty=!Object.values(cv).some(Boolean);return <article className="resume app-resume">{empty?<div className="empty-resume"><b>Your CV starts here.</b><p>Add personal information to build your live preview.</p></div>:<><header><h1>{cv.name||"YOUR NAME"}</h1><h2>{cv.role||"TARGET JOB TITLE"}</h2></header><p className="contact">{[cv.email,cv.phone,cv.location].filter(Boolean).join(" • ")}</p>{cv.summary&&<R title="Profile"><p>{cv.summary}</p></R>}{(cv.job||cv.company)&&<R title="Experience"><div className="resume-row"><div><h3>{cv.job}</h3><strong>{cv.company}</strong></div><time>{cv.dates}</time></div><ul>{cv.bullets.split("\n").filter(Boolean).map((x,i)=><li key={i}>{x}</li>)}</ul></R>}{(cv.degree||cv.school)&&<R title="Education"><h3>{cv.degree}</h3><strong>{cv.school}</strong></R>}{(cv.project||cv.projectText)&&<R title="Projects"><h3>{cv.project}</h3><p>{cv.projectText}</p></R>}{cv.skills&&<R title="Skills"><p>{cv.skills.split(",").map(s=>s.trim()).filter(Boolean).join(" • ")}</p></R>}</>}</article>}
