"use client";
import {useMemo,useRef,useState} from "react";
type CV={name:string;role:string;email:string;phone:string;location:string;link:string;summary:string;skills:string;job:string;company:string;dates:string;bullets:string;degree:string;school:string;eduDates:string;project:string;projectText:string;certification:string;certIssuer:string;activity:string;activityText:string};
const blank:CV={name:"",role:"",email:"",phone:"",location:"",link:"",summary:"",skills:"",job:"",company:"",dates:"",bullets:"",degree:"",school:"",eduDates:"",project:"",projectText:"",certification:"",certIssuer:"",activity:"",activityText:""};
const sample:CV={name:"Maya Perera",role:"Junior Software Engineer",email:"maya@email.com",phone:"+94 77 123 4567",location:"Colombo, Sri Lanka",link:"linkedin.com/in/mayaperera",summary:"Detail-oriented software engineering graduate with experience building accessible web applications and solving real user problems.",skills:"JavaScript, TypeScript, React, Next.js, Node.js, SQL, Git",job:"Software Engineering Intern",company:"Nova Digital",dates:"Jan 2025 — Jun 2025",bullets:"Built reusable React components that reduced development time by 25%.\nCollaborated with designers and engineers to deliver customer-facing features.\nImproved page performance and accessibility.",degree:"BSc (Hons) in Software Engineering",school:"University of Colombo",eduDates:"2021 — 2025",project:"Campus Connect",projectText:"Built a full-stack platform helping students discover clubs and university events.",certification:"Meta Front-End Developer",certIssuer:"Coursera • 2025",activity:"IEEE Student Branch",activityText:"Organized two technical workshops for more than 100 students."};
const tabs=["Personal","Summary","Education","Experience","Projects","Skills","Certifications","Activities","ATS","Match"] as const;type Tab=typeof tabs[number];
const stop=new Set(["the","and","for","with","that","this","from","your","you","are","our","will","have","has","into","but","not","job","role","work","team","using","who","their","they"]);
function tokens(s:string){return Array.from(new Set(s.toLowerCase().match(/[a-z][a-z0-9+#.-]{2,}/g)?.filter(x=>!stop.has(x))||[]))}
export default function Builder(){
 const[cv,setCv]=useState(blank),[tab,setTab]=useState<Tab>("Personal"),[mobile,setMobile]=useState<"edit"|"preview">("edit"),[jd,setJd]=useState(""),[paper,setPaper]=useState("a4"),[zoom,setZoom]=useState("fit"),[boundary,setBoundary]=useState(true),[orderOpen,setOrderOpen]=useState(false);const input=useRef<HTMLInputElement>(null);
 const set=(k:keyof CV,v:string)=>setCv(o=>({...o,[k]:v}));const issues=useMemo(()=>checks(cv),[cv]);const score=Math.max(10,100-issues.reduce((n,x)=>n+(x.kind==="error"?22:x.kind==="warning"?12:5),0));const cvText=Object.values(cv).join(" ");const jdt=tokens(jd),cvt=new Set(tokens(cvText));const matched=jdt.filter(x=>cvt.has(x)),missing=jdt.filter(x=>!cvt.has(x)).slice(0,18),match=jdt.length?Math.round(matched.length/jdt.length*100):0;
 const download=(content:string,type:string,name:string)=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)};
 const exportJson=()=>download(JSON.stringify(cv,null,2),"application/json","cvolt-cv.json");
 const importJson=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{setCv({...blank,...JSON.parse(String(r.result))})}catch{alert("Please select a valid CVOLT JSON file.")}};r.readAsText(f)};
 const word=()=>download("<html><body>"+document.querySelector(".app-resume")?.innerHTML+"</body></html>","application/msword","cvolt-cv.doc");
 return <main className="builder-app"><header className="app-header"><div className="app-head-main"><a className="brand app-brand" href="/"><span>CV</span>OLT<span className="brand-dot">.</span></a><div><div className="app-title-row"><h1>CV Builder</h1><span className="status-chip blue">✦ ATS ready</span><span className="status-chip green">● In-memory only</span></div><p>Live preview, ATS checks, and browser-only downloads.</p></div></div><div className="memory-note">◉ No autosave. Closing or refreshing clears current edits.</div><div className="app-actions"><button onClick={()=>confirm("Clear this CV and start again?")&&setCv(blank)}>↻ New CV</button><button onClick={()=>input.current?.click()}>↑ Import JSON</button><input hidden ref={input} type="file" accept="application/json" onChange={importJson}/><button onClick={exportJson}>{"{}"} Export JSON</button><button onClick={()=>setCv(blank)}>↻ Reset</button><button className="action-primary" onClick={()=>window.print()}>↓ PDF</button><button onClick={word}>⇩ Word</button></div></header>
 <div className="mobile-switch"><button className={mobile==="edit"?"active":""} onClick={()=>setMobile("edit")}>✎ Edit</button><button className={mobile==="preview"?"active":""} onClick={()=>setMobile("preview")}>▤ Preview</button></div>
 <div className="app-grid feature-grid"><aside className={"app-sidebar "+(mobile==="preview"?"mobile-off":"")}><nav>{tabs.map((t,i)=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}><span>{["◎","≡","◇","▣","▤","✦","♢","♧","▥","▧"][i]}</span>{t}<b>{done(t,cv)?"✓":""}</b></button>)}</nav><button className="order-toggle" onClick={()=>setOrderOpen(!orderOpen)}><b>Resume section order</b><span>{orderOpen?"Hide":"Show"}</span></button>{orderOpen&&<div className="order-panel">{["Summary","Experience","Education","Projects","Skills","Certifications","Activities"].map((x,i)=><div key={x}><span>{i+1}</span>{x}<small>↕</small></div>)}</div>}</aside>
 <section className={"editor-card "+(mobile==="preview"?"mobile-off":"")}><div className="editor-head"><div><small>{tab==="ATS"||tab==="Match"?"ANALYSIS":"SECTION "+(tabs.indexOf(tab)+1)+" OF 8"}</small><h2>{title(tab)}</h2><p>{help(tab)}</p></div>{!["ATS","Match"].includes(tab)&&<span>{done(tab,cv)?"✓ Complete":"In progress"}</span>}</div><div className="editor-body">
 {tab==="Personal"&&<><div className="app-form"><F label="Full name" value={cv.name} set={v=>set("name",v)} placeholder="YOUR NAME"/><F label="Target headline" value={cv.role} set={v=>set("role",v)} placeholder="TARGET JOB TITLE"/><F label="Email" value={cv.email} set={v=>set("email",v)} placeholder="name@example.com"/><F label="Phone" value={cv.phone} set={v=>set("phone",v)} placeholder="+94 70 123 4567"/><F label="Location" value={cv.location} set={v=>set("location",v)} placeholder="City, Country"/><F label="Profile link" value={cv.link} set={v=>set("link",v)} placeholder="linkedin.com/in/yourname"/></div></>}
 {tab==="Summary"&&<A label="Professional summary" value={cv.summary} set={v=>set("summary",v)} placeholder="Write 3–4 concise sentences tailored to the target role."/>}
 {tab==="Education"&&<div className="app-form"><F label="Degree / qualification" value={cv.degree} set={v=>set("degree",v)} placeholder="BSc in Software Engineering"/><F label="School / university" value={cv.school} set={v=>set("school",v)} placeholder="University name"/><F label="Dates" value={cv.eduDates} set={v=>set("eduDates",v)} placeholder="2021 — 2025"/></div>}
 {tab==="Experience"&&<div className="app-form"><F label="Job title" value={cv.job} set={v=>set("job",v)} placeholder="Software Engineering Intern"/><F label="Company" value={cv.company} set={v=>set("company",v)} placeholder="Company name"/><F label="Dates" value={cv.dates} set={v=>set("dates",v)} placeholder="Jan 2025 — Jun 2025"/><A label="Achievement bullets — one per line" value={cv.bullets} set={v=>set("bullets",v)} placeholder="Start with action verbs and include measurable results."/></div>}
 {tab==="Projects"&&<div className="app-form"><F label="Project name" value={cv.project} set={v=>set("project",v)} placeholder="Project name"/><A label="Project impact" value={cv.projectText} set={v=>set("projectText",v)} placeholder="Describe the problem, your contribution, tools, and result."/></div>}
 {tab==="Skills"&&<A label="Technical skills — separated with commas" value={cv.skills} set={v=>set("skills",v)} placeholder="JavaScript, React, Node.js, SQL, Git"/>}
 {tab==="Certifications"&&<div className="app-form"><F label="Certification" value={cv.certification} set={v=>set("certification",v)} placeholder="AWS Cloud Practitioner"/><F label="Issuer and year" value={cv.certIssuer} set={v=>set("certIssuer",v)} placeholder="Amazon Web Services • 2025"/></div>}
 {tab==="Activities"&&<div className="app-form"><F label="Leadership or activity" value={cv.activity} set={v=>set("activity",v)} placeholder="IEEE Student Branch"/><A label="Contribution and impact" value={cv.activityText} set={v=>set("activityText",v)} placeholder="Describe leadership, volunteering, or relevant campus activity."/></div>}
 {tab==="ATS"&&<div className="ats-panel"><div className="ats-score"><div><h3>ATS Readiness Estimate</h3><p>A general formatting and content estimate—not an official score from any specific ATS.</p></div><strong>{score}/100</strong></div><div className="progress"><i style={{width:score+"%"}}/></div>{issues.map((x,i)=><article className={"check "+x.kind} key={i}><div><b>{x.kind.toUpperCase()}</b><span>{x.section}</span></div><h4>{x.title}</h4><p>{x.text}</p></article>)}</div>}
 {tab==="Match"&&<div className="match-panel"><label><span>Paste job description</span><textarea rows={11} value={jd} onChange={e=>setJd(e.target.value)} placeholder="Paste a job description here. Processing stays in this browser."/></label><div className="match-score"><b>Keyword match estimate: {match}%</b><div className="progress"><i style={{width:match+"%"}}/></div><p>Only add keywords that truthfully represent your experience and skills.</p></div><h3>Matched keywords</h3><div className="keyword-list">{matched.length?matched.map(x=><span key={x}>{x}</span>):<p>No matched keywords yet.</p>}</div><h3>Potentially missing keywords</h3><div className="keyword-list missing">{missing.length?missing.map(x=><span key={x}>{x}</span>):<p>Paste a job description to compare.</p>}</div></div>}
 </div>{!["ATS","Match"].includes(tab)&&<div className="editor-footer"><button disabled={tabs.indexOf(tab)===0} onClick={()=>setTab(tabs[Math.max(0,tabs.indexOf(tab)-1)])}>← Previous</button><button className="action-primary" onClick={()=>{const i=tabs.indexOf(tab);setTab(tabs[Math.min(i+1,7)])}}>{tab==="Activities"?"Check ATS":"Save & continue →"}</button></div>}</section>
 <section className={"app-preview "+(mobile==="edit"?"mobile-off-preview":"")}><div className="preview-controls"><label>Paper size<select value={paper} onChange={e=>setPaper(e.target.value)}><option value="a4">A4 (210 × 297 mm)</option><option value="letter">US Letter (8.5 × 11 in)</option><option value="legal">US Legal (8.5 × 14 in)</option></select></label><label>Preview zoom<select value={zoom} onChange={e=>setZoom(e.target.value)}><option value="fit">Fit width</option><option value="75">75%</option><option value="90">90%</option><option value="100">100%</option></select></label><button disabled>‹ Previous</button><span>Page 1 of 1</span><button disabled>Next ›</button><label className="boundary"><input type="checkbox" checked={boundary} onChange={e=>setBoundary(e.target.checked)}/> Page boundary</label></div><div className={"preview-canvas "+(!boundary?"no-boundary":"")}><div className={"paper-scale zoom-"+zoom}><Resume cv={cv} paper={paper}/></div></div></section></div></main>
}
function checks(c:CV){return[...(!c.name?[{kind:"error",section:"Personal Information",title:"Add your full name",text:"A full name helps recruiters and parsers identify the CV owner."}]:[]),...(!(c.email||c.phone||c.link)?[{kind:"warning",section:"Personal Information",title:"Add contact information",text:"Include at least one email, phone, or profile link."}]:[]),...(!c.summary?[{kind:"warning",section:"Summary",title:"Add a professional summary",text:"A concise summary frames your CV for the target role."}]:[]),...(!c.degree?[{kind:"info",section:"Education",title:"Add education",text:"Include your most relevant qualification."}]:[]),...(!(c.job||c.project)?[{kind:"warning",section:"Evidence",title:"Show relevant evidence",text:"Add experience or a project that proves your capabilities."}]:[]),...(!c.skills?[{kind:"warning",section:"Skills",title:"Add technical skills",text:"Relevant keywords help recruiters understand your fit."}]:[])]}
function done(t:Tab,c:CV){return t==="Personal"?!!(c.name&&c.role&&c.email):t==="Summary"?!!c.summary:t==="Education"?!!(c.degree&&c.school):t==="Experience"?!!(c.job&&c.company):t==="Projects"?!!(c.project&&c.projectText):t==="Skills"?!!c.skills:t==="Certifications"?!!c.certification:t==="Activities"?!!c.activity:false}
function title(t:Tab){return t==="Skills"?"Technical Skills":t==="Activities"?"Leadership and Activities":t==="ATS"?"ATS Readiness Estimate":t==="Match"?"Job Description Keyword Match":t}
function help(t:Tab){return({Personal:"Contact details shown in the CV header.",Summary:"A concise introduction tailored to the role.",Education:"Add qualifications and relevant academic details.",Experience:"Describe roles with concise achievement bullets.",Projects:"Use portfolio, academic, or independent work.",Skills:"Skill groups export as plain ATS-friendly text.",Certifications:"Add certifications only when they truthfully apply.",Activities:"Leadership, volunteering, campus roles, or relevant activities.",ATS:"Review content and formatting recommendations.",Match:"Compare your CV with a job description locally."})[t]}
function F(p:{label:string;value:string;set:(v:string)=>void;placeholder:string}){return <label><span>{p.label}</span><input value={p.value} onChange={e=>p.set(e.target.value)} placeholder={p.placeholder}/></label>}
function A(p:{label:string;value:string;set:(v:string)=>void;placeholder:string}){return <label className="area-field"><span>{p.label}</span><textarea rows={8} value={p.value} onChange={e=>p.set(e.target.value)} placeholder={p.placeholder}/></label>}
function R({title,children}:{title:string;children:React.ReactNode}){return <section className="resume-section"><h2>{title}</h2>{children}</section>}
function Resume({cv,paper}:{cv:CV;paper:string}){const empty=!Object.values(cv).some(Boolean);return <article className={"resume app-resume paper-"+paper}>{empty?<div className="empty-resume"><b>Your CV starts here.</b><p>Add personal information to build your live preview.</p></div>:<><header><h1>{cv.name||"YOUR NAME"}</h1><h2>{cv.role||"TARGET JOB TITLE"}</h2></header><p className="contact">{[cv.email,cv.phone,cv.location,cv.link].filter(Boolean).join(" • ")}</p>{cv.summary&&<R title="Profile"><p>{cv.summary}</p></R>}{(cv.job||cv.company)&&<R title="Experience"><div className="resume-row"><div><h3>{cv.job}</h3><strong>{cv.company}</strong></div><time>{cv.dates}</time></div><ul>{cv.bullets.split("\n").filter(Boolean).map((x,i)=><li key={i}>{x}</li>)}</ul></R>}{(cv.degree||cv.school)&&<R title="Education"><div className="resume-row"><div><h3>{cv.degree}</h3><strong>{cv.school}</strong></div><time>{cv.eduDates}</time></div></R>}{(cv.project||cv.projectText)&&<R title="Projects"><h3>{cv.project}</h3><p>{cv.projectText}</p></R>}{cv.skills&&<R title="Technical Skills"><p>{cv.skills.split(",").map(s=>s.trim()).filter(Boolean).join(" • ")}</p></R>}{cv.certification&&<R title="Certifications"><h3>{cv.certification}</h3><p>{cv.certIssuer}</p></R>}{cv.activity&&<R title="Leadership and Activities"><h3>{cv.activity}</h3><p>{cv.activityText}</p></R>}</>}</article>}
