"use client";
import CvChecker from "../components/CvChecker";
import {track} from "../lib/analytics";
export default function Home(){const start=()=>{track("builder_open",{source:"landing_page"});window.location.assign("/builder")};return <main>
<section className="hero"><nav className="nav wrap"><a className="brand" href="#top"><span>CV</span>OLT<span className="brand-dot">.</span></a><div className="nav-pills"><span>100% free</span><span>No sign-up</span></div><button className="btn btn-dark" onClick={start}>Build my CV ↗</button></nav><div className="hero-grid wrap" id="top"><div><p className="eyebrow"><span>●</span> BUILT FOR STUDENTS & JOB SEEKERS</p><h1>Build a CV that gets past the <em>robots.</em></h1><p className="hero-sub">Create a clean, professional, ATS-friendly CV in minutes. No registration. No hidden fees. Your data stays private.</p><div className="hero-actions"><button className="btn btn-lime btn-large" onClick={start}>Create my free CV →</button><span className="micro">Takes about 5 minutes<br/><strong>No card required</strong></span></div><div className="trust-row"><span>✓ ATS-friendly</span><span>✓ Free PDF</span><span>✓ Private by design</span></div></div><div className="hero-card"><div className="float-badge badge-top">ATS READY <strong>98%</strong></div><div className="mini-resume"><header><div><b>MAYA PERERA</b><small>JUNIOR SOFTWARE ENGINEER</small></div><span>MP</span></header><div className="mini-line wide"/><div className="mini-line"/><h4>EXPERIENCE</h4><div className="mini-block"><b/><i/><i/></div><h4>EDUCATION</h4><div className="mini-block"><b/><i/></div><h4>SKILLS</h4><div className="mini-tags"><i/><i/><i/><i/></div></div><div className="float-badge badge-bottom">✓ No registration</div></div></div><div className="ticker">FREE FOREVER　✦　ATS-FRIENDLY　✦　NO REGISTRATION　✦　DOWNLOAD AS PDF　✦　YOUR DATA STAYS PRIVATE</div></section>
<CvChecker/>
<section className="how wrap"><p className="section-kicker">HOW IT WORKS</p><h2>From blank page to ready-to-send.</h2><div className="steps"><Step n="01" icon="✎" title="Add your details">Follow simple prompts for your experience, education, skills, and projects.</Step><Step n="02" icon="◫" title="Preview instantly">See every change live in a clean format designed for applicant tracking systems.</Step><Step n="03" icon="↓" title="Download & apply">Save a polished PDF and start applying with confidence. Completely free.</Step></div><div className="how-cta"><div><p className="section-kicker">READY TO START?</p><h2>Your next opportunity starts with a better CV.</h2></div><button className="btn btn-lime btn-large" onClick={start}>Build my free CV →</button></div></section>
<footer><div className="wrap"><div className="brand"><span>CV</span>OLT<span className="brand-dot">.</span></div><p>Built to help you get hired — free, private, and always accessible.</p><button className="btn btn-lime" onClick={start}>Build your CV →</button></div></footer></main>}
function Step({n,icon,title,children}:{n:string;icon:string;title:string;children:React.ReactNode}){return <article><b>{n}</b><span>{icon}</span><h3>{title}</h3><p>{children}</p></article>}
